Allow non-aligned PSTR()
earlephilhower/newlib-xtensa pull request #8
Opened 2020-05-07 21:22 UTC by s-hadinger

Report PR esp8266/Arduino#7275, but preserved the `__pstr__`

2020-05-07 22:18 UTC, earlephilhower approved these changes
Thx

2020-05-07 22:25 UTC, earlephilhower commented
I'll wait until the main Arduino PR gets merged in case we do something different for the UMM_INFO debug stuff.

2020-05-08 16:11 UTC, earlephilhower requested changes
Once the main core is approved again, please port that here so it doesn't get lost.  Thx!

2020-05-19 16:34 UTC, s-hadinger commented
Change from main core is now reported here.

2020-05-19 16:46 UTC, earlephilhower approved these changes

2020-05-19 16:46 UTC, merged